In [4]:
# 1/ 
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr, '\n')

print('Delete row 3 and 5:')  
print(np.delete(arr,[2,4],axis= 0))

print('Delete row 2,4,6 (use slice):')  
print(np.delete(arr,np.s_[1:6:2],axis=0))

print('Delete the last column:')  
print(np.delete(arr,[-1],axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 

Delete row 3 and 5:
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [16 17 18]]
Delete row 2,4,6 (use slice):
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
Delete the last column:
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]
 [13 14]
 [16 17]]


In [10]:
# 2/

import numpy as np 
arr = np.array([[3,9,6],[9,7,3],[6,8,9]]) 

print('Array:\n',arr,'\n') 

print('Xóa phần tử trùng lắp:')
u = np.unique(arr) 
print(u)

# Khôi phục array đã xóa
u,indices_inverse,counts = np.unique(arr,return_inverse = True,return_counts = True) 

del(arr)

print('Phục hồi array:')
print((u[indices_inverse]).reshape(3,3),'\n')

print('Số lần xuất hiện của các giá trị:')

print(u,'xuất hiện') 
print(counts,'lần')


Array:
 [[3 9 6]
 [9 7 3]
 [6 8 9]] 

Xóa phần tử trùng lắp:
[3 6 7 8 9]
Phục hồi array:
[[3 9 6]
 [9 7 3]
 [6 8 9]] 

Số lần xuất hiện của các giá trị:
[3 6 7 8 9] xuất hiện
[2 2 1 1 3] lần


In [14]:
#3/

import numpy as np 
arr = np.array([[3,9,6,7],[9,7,3,4],[6,8,9,12]])
print('Array:\n',arr,'\n') 

print('Các số chia hết cho 3:\n')
print('Cách 1:')
print(np.unique(arr[np.where(arr%3==0)]))
print('Cách 2:')
print(np.unique(np.extract(np.mod(arr,3)==0,arr)))

Array:
 [[ 3  9  6  7]
 [ 9  7  3  4]
 [ 6  8  9 12]] 

Các số chia hết cho 3:

Cách 1:
[ 3  6  9 12]
Cách 2:
[ 3  6  9 12]


In [16]:
#4/

import numpy as np 
arr = np.array([[3,9,6,7],[10,7,3,4],[6,8,9,12]])
print('Array:\n',arr,'\n') 

print('Số lớn nhất của mỗi dòng:')
print(np.max(arr,axis=1))

print('Số nhỏ nhất của mỗi cột:')
print(np.min(arr,axis=0))


Array:
 [[ 3  9  6  7]
 [10  7  3  4]
 [ 6  8  9 12]] 

Số lớn nhất của mỗi dòng:
[ 9 10 12]
Số nhỏ nhất của mỗi cột:
[3 7 3 4]


In [18]:
# 5/

import numpy as np
arr = np.array([6,3,5,9,2,4,7, 10, 15,14,16,18,19])
print('Array:\n', arr, '\n')

print('Sorted array:')
print(np.sort(arr))

number = int(input('Nhập 1 số bất kỳ từ 1->20: ')) # lưu ý :nhập số lớn hơn 10, nhỏ hơn 19, ví dụ nhập số 13

print('\nChèn number vào array mà không đổi thứ tự:')
a = np.sort(np.append(arr,number))
print(a)

Array:
 [ 6  3  5  9  2  4  7 10 15 14 16 18 19] 

Sorted array:
[ 2  3  4  5  6  7  9 10 14 15 16 18 19]

Chèn number vào array mà không đổi thứ tự:
[ 2  3  4  5  6  7  9 10 14 15 16 18 19 19]


In [22]:
# 6/
import numpy as np 
arr = np.array([[3,9,6,7],[10,7,3,4],[6,12,8,9]])
print('Array:\n',arr,'\n')

print('Sorted arr:')
print((np.sort(arr,axis=None)).reshape(3,4))

print('Sorted arr theo từng dòng:') 
print(np.sort(arr,axis=1)) 

print('Sorted arr theo từng cột:') 
print(np.sort(arr,axis=0)) 

Array:
 [[ 3  9  6  7]
 [10  7  3  4]
 [ 6 12  8  9]] 

Sorted arr:
[[ 3  3  4  6]
 [ 6  7  7  8]
 [ 9  9 10 12]]
Sorted arr theo từng dòng:
[[ 3  6  7  9]
 [ 3  4  7 10]
 [ 6  8  9 12]]
Sorted arr theo từng cột:
[[ 3  7  3  4]
 [ 6  9  6  7]
 [10 12  8  9]]


In [26]:
# 7/

import numpy as np 

'''
Lập data type cho member gồm:
HoTen kiểu dữ liệu: S10
TinhThanh kiểu dữ liệu: S10
ThuNhap kiểu dữ liệu: i4
'''
memberdtype = np.dtype([('HoTen','S10'),('TinhThanh', 'S10'), ('ThuNhap', 'i4')])

'''
Nhập dữ liêu với 5 người (nhập tùy ý)
'''
memberarr = np.array([('Tan','VT','200'),('Uyn','QB','100'),('Gau','VT','150'),('Meo','QB','300')],dtype= memberdtype)

print('Sắp xếp theo TinhThanh, HoTen, Thu Nhap ')
x = np.sort(memberarr,order=['TinhThanh','HoTen','ThuNhap'])
for item in x:
    print(item)

Sắp xếp theo TinhThanh, HoTen, Thu Nhap 
(b'Meo', b'QB', 300)
(b'Uyn', b'QB', 100)
(b'Gau', b'VT', 150)
(b'Tan', b'VT', 200)


In [23]:
# 8/
import numpy as np 
arr = np.array([[3,9,6,7],[10,7,3,4],[6,12,8,9]])
print('Array:\n',arr,'\n')

x = np.sort(arr,axis=1)
print(x)


Array:
 [[ 3  9  6  7]
 [10  7  3  4]
 [ 6 12  8  9]] 

[[ 3  6  7  9]
 [ 3  4  7 10]
 [ 6  8  9 12]]
