In [1]:
#1/ numpy ufunc
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([7, 8, 9, 10, 11, 12])
arr3 = np.array([13, 14, 5, 16, 17, 18])

newarr = np.sum([arr1,arr2,arr3],axis= 0)

print(newarr)

[21 24 17 30 33 36]


In [9]:
#2/  y = a*x + b
import numpy as np

x = np.array([1, 2, 3, 4])

def bai2(a,b,x):
    return a*x +b

a = 2
b = 3
bai2 = np.frompyfunc(bai2,3,1)
y = bai2(a,b,x)
# y = a*x +b
print(y)
print(type(bai2))

[5 7 9 11]
<class 'numpy.ufunc'>


In [7]:
#3/ min, max 
import numpy as np

arr1 = np.array([10, 7, 30, 40, 2, 60])
arr2 = np.array([3, 20, 9, 8, 50, 33])

def findminmax(arr1, arr2):
    return np.minimum(arr1, arr2), np.maximum(arr1, arr2)

findminmax = np.frompyfunc(findminmax,2,2)

amin, amax = findminmax(arr1, arr2)

print('array min:', amin,'\n')
print('array max:', amax,'\n')

print('findminmax:', type(findminmax))

array min: [3 7 9 8 2 33] 

array max: [10 20 30 40 50 60] 

findminmax: <class 'numpy.ufunc'>


In [12]:
#4/

import numpy as np 

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('a:\n', a,'\n')

b = np.array([1,2,3])

print('Cộng cột a và b:\n')

print(np.add(a,b))


a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Cộng cột a và b:

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [13]:
#5/
import numpy as np

a = np.array([-4.356, 2.738])

print('Làm tròn 1 chữ số sau phần thập phân:', np.round(a,2),'\n')
print('Lây phần nguyên trên', np.ceil(a),'\n')
print('Lấy phần nguyên dưới:', np.floor(a),'\n')
print('Lấy phần nguyên gần 0 nhất:', np.fix(a),'\n')

Làm tròn 1 chữ số sau phần thập phân: [-4.36  2.74] 

Lây phần nguyên trên [-4.  3.] 

Lấy phần nguyên dưới: [-5.  2.] 

Lấy phần nguyên gần 0 nhất: [-4.  2.] 



In [14]:
# 6/ Tính log6(x)

from math import log
import numpy as np

x = np.array([6, 36, 216])
nplog = np.frompyfunc(log, 2, 1)
print(nplog(x,6))

[1.0 2.0 3.0000000000000004]


In [15]:
#7/ #sum, cumsum
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print('a:\n',a,'\n')
print('b:\n',b,'\n')

newarr1 = np.sum([a,b],axis = 1)
print('newarr:\n', newarr1,'\n')

newarr2 = np.sum([a,b],axis = 0)
print('newarr2:\n', newarr2, '\n')

x = np.array([[1, 2], [3, 4]])
newarr3 = (np.cumsum(x)).reshape(2,2)
print('newarr3:\n', newarr3)

a:
 [[1 2]
 [3 4]] 

b:
 [[5 6]
 [7 8]] 

newarr:
 [[ 4  6]
 [12 14]] 

newarr2:
 [[ 6  8]
 [10 12]] 

newarr3:
 [[ 1  3]
 [ 6 10]]


In [17]:
# 8/ 
import numpy as np

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

newarr = np.prod([arr1,arr2])
newarr1 = np.prod([arr1,arr2],axis=1)
newarr2 = np.prod([arr1,arr2],axis=0)

print('newarr:', newarr, '\n')
print('newarr1:', newarr1, '\n')
print('newarr2:', newarr2, '\n')


newarr: 24 

newarr1: [ 2 12] 

newarr2: [3 8] 



In [18]:
#9/

import numpy as np

arr = np.array([8, 32, 36, 16])

print('Bội số chung nhỏ nhât:', np.lcm.reduce(arr) ,'\n')
print('Ước số chung lớn nhất:', np.gcd.reduce(arr) ,'\n')

Bội số chung nhỏ nhât: 288 

Ước số chung lớn nhất: 4 



In [19]:
#10/
import numpy as np

arr1 = np.array([4, 6, 2, 3,  4])
arr2 = np.array([4, 6, 2, 1, 6])

print('Phần tử riêng của arr1 và arr2:', np.setxor1d(arr1, arr2, assume_unique = True))
print('Phần tử chung:', np.intersect1d(arr1, arr2, assume_unique = False))
print('Phần tử trong arr1 không có trong arr2:',np.setdiff1d(arr1, arr2, assume_unique = True))

Phần tử riêng của arr1 và arr2: [1 3]
Phần tử chung: [2 4 6]
Phần tử trong arr1 không có trong arr2: [3]
