In [ ]:
NumPy ufuncs

ufuncs stands for "Universal Functions" and they are NumPy functions that operates on the ndarray object.

-----

Why use ufuncs?
ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

-----

What is Vectorization?
Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

In [1]:
# Without ufunc, we can use Python's built-in zip() method:

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [2]:
#ufunc: add()

import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [ ]:
1/ Create Your Own ufunc: np.frompyfunc()
    
The frompyfunc() method takes the following arguments:

function - the name of the function.
inputs - the number of input arguments (arrays).
outputs - the number of output arrays.

In [4]:
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

print(type(myadd))

[6 8 10 12]
<class 'numpy.ufunc'>


In [6]:
import numpy as np

print(type(np.add))

print(type(np.concatenate))

<class 'numpy.ufunc'>
<class 'function'>


In [ ]:
2/ Simple Arithmetic: + - * /

In [11]:
# add()

import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [14]:
import numpy as np

arr1 = np.array([[10, 11, 12], [13, 14, 15]])
arr2 = np.array([[20, 21, 22], [23, 24, 25]])

newarr = np.add(arr1, arr2)

print(newarr)

[[30 32 34]
 [36 38 40]]


In [8]:
# subtract() = minus

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [15]:
# multiply()


arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [16]:
# divide()

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [19]:
# power()

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([3, 5, 6, 8, 2, 4])

newarr = np.power(arr1, arr2)

print(newarr)

[    1    32   729 65536    25  1296]


In [20]:
# mod() and the remainder()

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [2]:
# divmod() 
# divmod() function return both the quotient and the the mod
# The return value is two arrays, the first array contains the quotient
# and second array contains the mod.

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr, '\n')
print(newarr[0])
print(newarr[1])

(array([ 3,  2,  3,  5, 25,  1], dtype=int32), array([ 1,  6,  3,  0,  0, 27], dtype=int32)) 

[ 3  2  3  5 25  1]
[ 1  6  3  0  0 27]


In [24]:
# absolute() and the abs()
# we should use absolute() to avoid confusion with python's inbuilt math.abs()

import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


In [31]:
import numpy as np 
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print('First array:\n', a,'\n') 

b = np.array([10,10,10])
#b = np.array([10])
#b = 10
#b = np.array([[10,10,10]]).T
print('Second array:\n', b, '\n') 

print('Add the two arrays:\n', np.add(a,b), '\n') 

print('Subtract the two arrays:\n', np.subtract(a,b), '\n')

print('Multiply the two arrays:\n', np.multiply(a,b), '\n')

print('Divide the two arrays:\n', np.divide(a,b))

First array:
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]] 

Second array:
 [10 10 10] 

Add the two arrays:
 [[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]] 

Subtract the two arrays:
 [[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]] 

Multiply the two arrays:
 [[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]] 

Divide the two arrays:
 [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [32]:
import numpy as np 
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print('First array:\n', a,'\n') 

b = np.array([8,9,10])
print('Second array:\n', b, '\n') 

print('Add the two arrays:\n', np.add(a,b), '\n') 

print('Subtract the two arrays:\n', np.subtract(a,b), '\n')

print('Multiply the two arrays:\n', np.multiply(a,b), '\n')

print('Divide the two arrays:\n', np.divide(a,b))

First array:
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]] 

Second array:
 [ 8  9 10] 

Add the two arrays:
 [[ 8. 10. 12.]
 [11. 13. 15.]
 [14. 16. 18.]] 

Subtract the two arrays:
 [[-8. -8. -8.]
 [-5. -5. -5.]
 [-2. -2. -2.]] 

Multiply the two arrays:
 [[ 0.  9. 20.]
 [24. 36. 50.]
 [48. 63. 80.]] 

Divide the two arrays:
 [[0.         0.11111111 0.2       ]
 [0.375      0.44444444 0.5       ]
 [0.75       0.77777778 0.8       ]]


In [34]:
import numpy as np 
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print('First array:\n', a,'\n') 

b = np.array([[8,9,10]]).T
print('Second array:\n', b, '\n') 

print('Add the two arrays:\n', np.add(a,b), '\n') 

print('Subtract the two arrays:\n', np.subtract(a,b), '\n')

print('Multiply the two arrays:\n', np.multiply(a,b), '\n')

print('Divide the two arrays:\n', np.divide(a,b))

First array:
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]] 

Second array:
 [[ 8]
 [ 9]
 [10]] 

Add the two arrays:
 [[ 8.  9. 10.]
 [12. 13. 14.]
 [16. 17. 18.]] 

Subtract the two arrays:
 [[-8. -7. -6.]
 [-6. -5. -4.]
 [-4. -3. -2.]] 

Multiply the two arrays:
 [[ 0.  8. 16.]
 [27. 36. 45.]
 [60. 70. 80.]] 

Divide the two arrays:
 [[0.         0.125      0.25      ]
 [0.33333333 0.44444444 0.55555556]
 [0.6        0.7        0.8       ]]


In [41]:
#reciprocal() : Nghịch đảo
import numpy as np 
a = np.array([0.25, 1.33, 1, 0, 100]) 

print('Our array is:\n', a, '\n')   

print('After applying reciprocal function:\n', np.reciprocal(a), '\n')

b = np.array([100], dtype = int)
#b = np.array([100], dtype = float)
print('The second array is:\n', b, '\n') 

print('After applying reciprocal function:\n', np.reciprocal(b) )


Our array is:
 [  0.25   1.33   1.     0.   100.  ] 

After applying reciprocal function:
 [4.        0.7518797 1.              inf 0.01     ] 

The second array is:
 [100] 

After applying reciprocal function:
 [0]


<ipython-input-41-9f59583309e9>:10: RuntimeWarning: divide by zero encountered in reciprocal
  print('After applying reciprocal function:\n', np.reciprocal(a), '\n')


In [ ]:
# 3/ Rounding Decimals
truncation
fix
rounding
floor
ceil

In [42]:
# trunc : Làm tròn xuống gần số 0

import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [3]:
# fix() :Làm tròn xuống gần số 0

import numpy as np

arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [45]:
# around() : Làm tròn theo ... số

import numpy as np

arr = np.around(3.1666, 2)
print(arr)

arr1 = np.around([-3.1666, 3.6667], 2)
print(arr1)

3.17
[-3.17  3.67]


In [46]:
# floor() :Làm tròn lùi 1 đơn vị./ Lấy phần nguyên dưới

import numpy as np

arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [47]:
# ceil() :Làm tròn lên 1 đơn vị. / Lây phần nguyên trên

import numpy as np

arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


In [ ]:
4/ Logs: log2, log10, log, log any base

In [48]:
# Log at Base 2

import numpy as np

arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [49]:
# Log at Base 10

import numpy as np

arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [50]:
# Natural Log, or Log at Base e

import numpy as np

arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [1]:
# Log at Any Base
# NumPy does not provide any function to take log at any base,
# so we can use the frompyfunc() function along with inbuilt function math.log()
# with two input parameters and one output parameter:

from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(np.array([[100],[200]]), 15),'\n')
print(np.power(15, nplog(100, 15)))

[[1.7005483074552052]
 [1.9565063322650205]] 

100.00000000000001


In [6]:
from math import log
import numpy as np

log_np= np.frompyfunc(log, 2, 1)
print(np.around(log_np(100,15),2))

1.7


In [ ]:
# 5/ Summations: sum, cumsum

In [59]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [60]:
# sum()

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [70]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=0)

print(newarr)

[2 4 6]


In [61]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [62]:
# cumsum()

import numpy as np

arr = np.array([1, 2, 3])

newarr = np.cumsum(arr) # [1, 1+2, 1+2+3]

print(newarr)

[1 3 6]


In [ ]:
6/ Products: prod(), cumprod()

In [63]:
# prod()
import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [64]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2]) # 1*2*3*4*5*6*7*8

print(x)

40320


In [68]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=0)

print(newarr)

[ 5 12 21 32]


In [69]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [71]:
# cumprod()

import numpy as np

arr = np.array([1, 2, 3, 4])

newarr = np.cumprod(arr) # [1, 1*2, 1*2*3, 1*2*3*4]

print(newarr)

[ 1  2  6 24]


In [72]:
# 7/ Differences

import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr) # 15-10=5, 25-15=10, and 5-25=-20

print(newarr)

[  5  10 -20]


In [73]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2) # 15-10=5, 25-15=10, and 5-25=-20 => [5 10 -20], 10-5=5, -20-10=-30 =>[5, -30]

print(newarr)

[  5 -30]


In [76]:
# LCM Lowest Common Multiple

In [78]:
import numpy as np

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12
<class 'numpy.ufunc'>


In [79]:
import numpy as np

arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


In [80]:
import numpy as np

arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


In [ ]:
# 9/ GCD Greatest Common Denominator

In [81]:
import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [82]:
import numpy as np

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


In [ ]:
# 10/ Trigonometric Functions

In [ ]:
# sin(), cos() and tan()

In [83]:
import numpy as np

x = np.sin(np.pi/2)

print(x)

1.0


In [84]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [85]:
# Convert Degrees Into Radians

import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [86]:
# Radians to Degrees

import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


In [ ]:
# arcsin(), arccos() and arctan()

In [87]:
import numpy as np

x = np.arcsin(1.0)

print(x)

1.5707963267948966


In [88]:
import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [89]:
# Hypotenues : Tìm cạnh thứ 3 trong tam giác Pitago
# hypot() function that takes the base and perpendicular values
# and produces hypotenues based on pythagoras theorem

import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


In [ ]:
# 11/ Set Operations

In [90]:
# unique() : Tổng hợp các phần tử không trùng nhau
# to find unique elements from any array. E.g. create a set array,
# but remember that the set arrays should only be 1-D arrays.

import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [91]:
# union1d() : Tổng hợp các phần tử 2 array không trùng nhau

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [97]:
# intersect1d() : Chọn các phần tử trùng nhau ở 2 array
# Phần tử chung
import numpy as np

arr1 = np.array([1, 2, 3, 3,  4])
arr2 = np.array([3, 4, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)
# intersect1d() method takes an optional argument assume_unique,
# which if set to True can speed up computation.
# It should always be set to True when dealing with sets.

print(newarr)

[3 3 4 4]


In [98]:
import numpy as np

arr1 = np.array([1, 2, 3, 3,  4])
arr2 = np.array([3, 4, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=False)

print(newarr)

[3 4]


In [93]:
# setdiff1d()
# Phần tử trong set1 không có trong set2
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


In [104]:
# setxor1d()
# Phần tử riêng của set1 và set2
import numpy as np

set1 = np.array([1, 2, 3, 3, 4])
set2 = np.array([3, 4, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
